server:
  port: 8899
  http2:
    enabled: true
management:
  endpoints:
    web:
      base-path: /application

spring:
  application:
    name: simple-messaging

logging:
  file:
    path: logs/${spring.application.name}